### ISSUE TITLE
Internal Server Error when calling get_organizations

### ISSUE THREAD

**Issue by DianaTolstyga** [GregEremeev/gosuslugi-api#1]
If one calls get_organizations(self, inn) method, it is shown HTTP Status 403 - Access Denied error which means that the access is forbidden.
Could you please advise how to deal with this issue?
 [Get_organizations(self, INN)](https://dom.gosuslugi.ru/ppa/api/rest/services/ppa/organizations/chooser/search;page=1;itemsPerPage=11) 

Thanks

**Comment by GregEremeev** [comment]
Hello @DianaTolstyga.

Thanks for your interest in this library.

If you want to get information about any organization by INN then you need to use `get_organizations` method.

If you pay attention to the implementation of this method then you will see that it uses `POST` method.
So, I guess, developers of gosuslugi didn't expose `GET` method for this endpoint without an authentification.

Anyway if you need info about an organization you need to do this

```
In [8]: from gosuslugi_api.clients import GosUslugiAPIClient
In [9]: client = GosUslugiAPIClient()
In [10]: client.get_organizations('7724480900')
```

Your INN has to be from their DB, your can find them [here](https://dom.gosuslugi.ru/#!/licenses)

**Comment by DianaTolstyga** [comment]
Thank you very much, @GregEremeev, the code works now!

**Comment by GregEremeev** [comment]
The issue was resolved
