### ISSUE TITLE
Limited information when calling get_actual_houses and get_organization

### ISSUE THREAD

**Issue by DianaTolstyga** [GregEremeev/gosuslugi-api#2]
Methods get_actial_houses and get_organization work well but do not show all the detailed information which gosuslugi portal provides. I.e. the portal gives many details on a specified house incl its address, type of house, cadastre number, construction year, size of building, condition etc. While get_actual_houses method gives only data on house condition.  The same story with get_organization method.
Could you please advise how to get all relevant information?
Thanks
[portal data on a specified house](https://dom.gosuslugi.ru/#!/house-view?guid=a5893115-8e9d-4b4c-9fd6-9aa07fd59053&typeCode=1) 

[data received through get_actual_houses method]
<img width="635" alt="Screenshot 2021-05-03 at 12 04 46" src="https://user-images.githubusercontent.com/71463553/116901388-dc8e6480-ac07-11eb-95a9-5064a2bba0c6.png">

**Comment by GregEremeev** [comment]
Hello @DianaTolstyga

>Methods get_actial_houses and get_organization work well but do not show all the detailed information which gosuslugi portal provides.

I think you meant `get_actial_houses` and `get_organizationS`.
They are not supposed to show all information cause they take data from `collections` endpoints.
If you need to obtain more information on a particular object then you need to use methods that take data from endpoints with detailed data.

>portal data on a specified house

If you want to obtain data from this page then you need to use `get_home_management` method

`client.get_home_management('a5893115-8e9d-4b4c-9fd6-9aa07fd59053')`

**Comment by GregEremeev** [comment]
Well, I guess, I can write README with examples of every method.
If you are going to use this library.

**Comment by DianaTolstyga** [comment]
Hi @GregEremeev ,
Thank you very much for your prompt response and very useful tips.  
Absolutely, readme with examples would be very useful!
 I found it a bit challenging to put the right arguments for the methods (i.e. which guid should I use as an org_guid argument for get_home_managements method since organization's guid does not work: client.get_home_managements(‘4105ee91-9191-4840-b788-f3d4db7c5f1b’))

**Comment by DianaTolstyga** [comment]
@GregEremeev Could you please advise if there is a chance to get the list of houses managed by certain organization? 

In my task I have a list of 1000 INNs and I have to get detailed house data (provided by get_home_management method) for all houses managed by the organization with a specified inn.

**Comment by GregEremeev** [comment]
>I found it a bit challenging to put the right arguments for the methods

Yes, without knowing the API it's not simple.

>Could you please advise if there is a chance to get the list of houses managed by certain organization?

Yes, it's possible. All organizations are obliged to send actual information about houses, which they manage, to `ГИС ЖКХ`.
You need to use `get_licenses` method to obtain xlsx files with this information(look at the README). If you know a `region` and `inn` of your organization, It will be enough to find *`every house`, which is managed by the organization.

* you will be able to obtain only houses, which about an organization decided to notify `ГИС ЖКХ`.<br>In most all cases, you will find all managed houses but sometimes some of them could be missing on purpose.

**Comment by GregEremeev** [comment]
I release 0.6.0 version, use it.

**Comment by DianaTolstyga** [comment]
Thank you for the support @GregEremeev!  README and the updated version are very much appreciated!

Although my code taken from README couldn't pick up the new 0.6.0 version and its get_licenses method, need some time to figure out why.. But could you please confirm that get_licenses would be able to give house data: either the detailed list of house data (incl. cadastre number, total square, building year etc.) or at least home_management_guid (with which I could get all the details through get_home_management method)?
Thank you @GregEremeev

**Comment by GregEremeev** [comment]
>Thank you for the support @GregEremeev! README and the updated version are very much appreciated!

Don't forget to add a star to this library.

>Although my code taken from README couldn't pick up the new 0.6.0 version and its get_licenses method, need some time to figure out why..

That's because you are not aware of how to manage Python's dependencies via `pip`
[Read this](https://packaging.python.org/tutorials/installing-packages/#creating-virtual-environments)
and always use python environment to work with Python.

>But could you please confirm that get_licenses would be able to give house data: 

`get_licenses` is a start. It gives you a list of houses for some specific regions. From this list, you can get mapping `organization - building`. You can get all the necessary ids from this list to get detailed information for a specific building or management company or organization via other methods.

You just need to install the correct version of this library and play with examples from README.

**Comment by GregEremeev** [comment]
@DianaTolstyga you are welcome.

I'll mark this issue as solved. If you have any other questions you can create another one.
