### ISSUE TITLE
street guids and house guids

### ISSUE THREAD

**Issue by onyx-zup** [GregEremeev/gosuslugi-api#4]
Добрый день!
Я знаю как добавить получение guid улицы по ее названию, а так же получение guid всех домов по улице. Могу поделиться.

**Comment by GregEremeev** [comment]
Hello @onyx-zup 

If you are ready to create a MR to add additional functionality then I'll consider it.

**Comment by onyx-zup** [comment]
ok, need some time to implement

**Comment by onyx-zup** [comment]
BUT there is a question. I need a method to get cityCode and regionCode like cityCode=b502ae45-897e-4b6f-9776-6ff49740b537 regionCode=18133adf-90c2-438e-88c4-62c41656de70. I have found it for my region and city, but we need some list of codes, like REGION_CODES_AND_NAMES, or some api to get it as search results. Will find out

**Comment by onyx-zup** [comment]
Got it

**Comment by onyx-zup** [comment]
I have done it and locally committed changes, but don't know how to push  changes! The error in my pycharm looks like
17:42:52.974: [gosuslugi-api] git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/master:master
remote: Permission to GregEremeev/gosuslugi-api.git denied to onyx-zup.
fatal: unable to access 'https://github.com/GregEremeev/gosuslugi-api.git/': The requested URL returned error: 403

**Comment by GregEremeev** [comment]
>I have done it and locally committed changes, but don't know how to push changes!

Because you don't know how to work with `git` and `GitHub`.
Google something like `how to create a pull request to some repository`

**Comment by onyx-zup** [comment]
Sorry, it is too much for me. Here is a patch if u want to: 
https://pastebin.com/MVmPmb7z

**Comment by GregEremeev** [comment]
Yeah, nobody said that be a software engineer is simple 😅
